theme: jekyll-theme-minimal
title: Phi Nguyen's Portfolio
description: Portfolio for PROG 101
logo: "https://raw.githubusercontent.com/feelittlebear/Phi-Nguyen.github.io/refs/heads/master/images/Phi%20cool%20image%20for%20github.JPG" # your photo (or logo) here
